cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    khalil:
      email: khalil.mhirsi@hotmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Khalil
      password: $2b$12$Zr4fIXblgIpmjuIegap91u0.O9MJtDm702O12uc0OiwA27.WE5/7e
    sophia:
      email: khalil.mhirsi@hotmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Sophia
      password: $2b$12$f8PHwOocFmezzXvtOMfQqev2Rns6JcAcr0sPWWWhR794qnC8yaXNC
pre-authorized:
  emails:
  - melsby@gmail.com
