[server]
headless = true
runOnSave = true
port = 8501
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[runner]
fastReruns = true
